// lib/pg-hardening/analyzer.ts

import { PG_RULES, type PGResult, type Severity } from "./rules";

export type ScanStatus = "PASS" | "PARTIAL" | "FAIL";
export type RiskLabel  = "Excellent" | "Good" | "Needs Improvement" | "High Risk";

export interface ScoreBreakdown {
  high: number; medium: number; low: number; passed: number;
}

export interface PGScanResult {
  results:    PGResult[];
  counts:     Record<Severity | "passed", number>;
  score:      number;
  status:     ScanStatus;
  riskLabel:  RiskLabel;
  message:    string;
  breakdown:  ScoreBreakdown;
  byCategory: Record<string, PGResult[]>;
}

const PENALTY: Record<Severity, number> = { high: 10, medium: 5, low: 2 };

const STATUS_MESSAGES: Record<ScanStatus, string> = {
  FAIL:    "This configuration contains high-risk issues that should be fixed immediately.",
  PARTIAL: "This configuration is partially hardened but still has security gaps.",
  PASS:    "This configuration follows most PostgreSQL security best practices.",
};

function computeScore(b: ScoreBreakdown): number {
  let score = 100 - b.high * 10 - b.medium * 5 - b.low * 2;
  if      (b.high >= 3) score = Math.min(score, 40);
  else if (b.high === 2) score = Math.min(score, 50);
  else if (b.high === 1) score = Math.min(score, 70);
  return Math.max(0, score);
}

function computeStatus(b: ScoreBreakdown): ScanStatus {
  if (b.high > 0)   return "FAIL";
  if (b.medium > 0) return "PARTIAL";
  return "PASS";
}

function computeRiskLabel(score: number): RiskLabel {
  if (score >= 90) return "Excellent";
  if (score >= 70) return "Good";
  if (score >= 50) return "Needs Improvement";
  return "High Risk";
}

export function scanConfigs(pgConf: string, hbaConf: string): PGScanResult {
  const results: PGResult[] = PG_RULES.map((rule) => {
    let passed = true;
    try { passed = !rule.check(pgConf, hbaConf); } catch { /* skip */ }
    return { rule, passed };
  });

  const counts: Record<Severity | "passed", number> = { high: 0, medium: 0, low: 0, passed: 0 };
  const byCategory: Record<string, PGResult[]> = {};

  for (const r of results) {
    r.passed ? counts.passed++ : counts[r.rule.severity]++;
    (byCategory[r.rule.category] ??= []).push(r);
  }

  const breakdown: ScoreBreakdown = {
    high: counts.high, medium: counts.medium, low: counts.low, passed: counts.passed,
  };
  const score     = computeScore(breakdown);
  const status    = computeStatus(breakdown);

  return {
    results, counts, score, status,
    riskLabel: computeRiskLabel(score),
    message:   STATUS_MESSAGES[status],
    breakdown, byCategory,
  };
}

export function generateQuickFix(results: PGResult[]): string {
  const fixes = results
    .filter((r) => !r.passed)
    .sort((a, b) => {
      const order: Severity[] = ["high", "medium", "low"];
      return order.indexOf(a.rule.severity) - order.indexOf(b.rule.severity);
    })
    .map((r) => `# Fix [${r.rule.id}] ${r.rule.title}\n${r.rule.config_fix}`)
    .join("\n\n");
  return fixes || "# No issues found — no fixes needed.";
}

export function generateHardenedPGConf(): string {
  return `# ═══════════════════════════════════════════════════════════
# Hardened postgresql.conf — CIS-style PostgreSQL Security
# Generated by PostgreSQL Hardening Checker — damonsec.com
# Validate by restarting PostgreSQL and checking logs
# ═══════════════════════════════════════════════════════════

# ── Connections ──────────────────────────────────────────
listen_addresses = 'localhost'          # 1.1 — no wildcard binding
port             = 5432
max_connections  = 100                  # 2.3 — prevent connection exhaustion

# ── Authentication ───────────────────────────────────────
password_encryption = 'scram-sha-256'  # 2.1 — strong password hashing

# ── SSL/TLS ──────────────────────────────────────────────
ssl                     = on                    # 1.3
ssl_cert_file           = '/etc/postgresql/server.crt'
ssl_key_file            = '/etc/postgresql/server.key'
ssl_ca_file             = '/etc/postgresql/root.crt'
ssl_min_protocol_version = 'TLSv1.2'           # 2.6 — no legacy TLS
ssl_ciphers             = 'HIGH:MEDIUM:+3DES:!aNULL'

# ── Memory ───────────────────────────────────────────────
shared_buffers      = 256MB    # 3.1 — 25% of RAM, adjust to your system
effective_cache_size = 1GB     # 50–75% of RAM
work_mem            = 4MB

# ── Timeouts ─────────────────────────────────────────────
idle_in_transaction_session_timeout = 60000   # 3.6 — 60s idle tx timeout
statement_timeout                   = 30000   # 30s query timeout
lock_timeout                        = 10000   # 10s lock wait timeout

# ── Logging ──────────────────────────────────────────────
logging_collector          = on                # 2.2
log_directory              = 'pg_log'
log_filename               = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_rotation_age           = 1d
log_rotation_size          = 100MB
log_min_duration_statement = 1000              # 2.5 — log slow queries (>1s)
log_checkpoints            = on
log_connections            = on                # 3.3
log_disconnections         = on
log_lock_waits             = on
log_statement              = 'ddl'             # 3.2 — log all DDL
log_replication_commands   = on
log_line_prefix            = '%m [%p] %q%u@%d '  # 3.5 — structured prefix
log_timezone               = 'UTC'

# ── Security ─────────────────────────────────────────────
# Prevent functions from running OS commands unless explicitly needed
#row_security = on  # Enable row-level security globally

# Track query activity
track_activities    = on
track_counts        = on
track_io_timing     = on`;
}

export function generateHardenedHBAConf(): string {
  return `# ═══════════════════════════════════════════════════════════
# Hardened pg_hba.conf — CIS-style PostgreSQL Access Control
# Generated by PostgreSQL Hardening Checker — damonsec.com
# ═══════════════════════════════════════════════════════════
#
# FORMAT: type  database  user  address  method
#
# Auth methods (strongest to weakest):
#   scram-sha-256  — recommended for all network connections
#   peer           — maps OS user to DB user (local socket only)
#   reject         — explicitly deny
#   md5            — deprecated, avoid
#   trust          — NEVER use in production

# ── Local socket connections ─────────────────────────────
# OS users mapped to DB users via peer authentication
local  all             postgres                 peer    # 1.4 — superuser local only
local  all             all                      peer    # standard local access

# ── IPv4 localhost ───────────────────────────────────────
host   all             all       127.0.0.1/32   scram-sha-256

# ── IPv6 localhost ───────────────────────────────────────
host   all             all       ::1/128         scram-sha-256

# ── Application server connections ──────────────────────
# Replace with your actual app server IP range:
host   mydb            appuser   10.0.1.0/24    scram-sha-256  # 1.5 — no 0.0.0.0/0

# ── Replication (if needed) ──────────────────────────────
# host   replication     replicator  10.0.0.2/32  scram-sha-256

# ── Reject everything else ───────────────────────────────
host   all             all       0.0.0.0/0      reject
host   all             all       ::/0           reject`;
}